name: Deploy
on:
  push:
    branches: [harrymander/release/1.11.0]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: harrymander
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setup node and build the frontend. For some reason Label Studio checks
      # the built frontend into source control, and the Docker image build
      # doesn't seem to properly build in the changes to the frontend unless
      # they are built locally first.
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: yarn
          cache-dependency-path: ./web/yarn.lock
      - name: Install yarn dependencies
        working-directory: ./web
        run: yarn install --frozen-lockfile
      - name: Build frontend
        working-directory: ./web
        run: yarn build

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/label-studio:latest
